schema_version: 1

context:
  name: schemathesis
  version: "4.26.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/schemathesis-${{ version }}.tar.gz
  sha256: b5e9419f9980aef89435c401cbb93b53291d44e7b1e5de8f86008ac7f93ae722

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - schemathesis = schemathesis.cli:schemathesis
      - st = schemathesis.cli:schemathesis

requirements:
  host:
    - pip
    - hatchling
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - click >=8.0,<9
    - harfile >=0.5.0,<1.0
    - hypothesis >=6.130.12,<7
    - hypothesis-graphql >=0.13.2
    - jsonschema-rs >=0.55.0
    - pyrate-limiter >=4.0,<5.0
    - pytest >=9,<10
    - pyyaml >=5.1,<7.0
    - requests >=2.22,<3
    - rich >=13.9.4
    - anyio >=4.5,<5
    - tomli >=2.2.1
    - typing_extensions >=4.12.2
    - werkzeug >=0.16.0,<4

tests:
  - python:
      imports:
        - schemathesis
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - schemathesis --help
      - st --help

about:
  summary: Property-based testing framework for Open API and GraphQL based apps
  license: MIT
  license_file:
    - LICENSE
  homepage: https://github.com/schemathesis/schemathesis
  documentation: https://schemathesis.readthedocs.io/

extra:
  recipe-maintainers:
    - Stranger6667
    - thewchan
